server:
  port: 9595

zuul:
  routes:
    user:
      path: /user/**
      url: http://localhost:8787/user
    docs:
        path: /pomelos_docs/**
        url: http://192.168.7.73:80/pomelos_docs
    doc_test:
      path: /doc_test/**
      url: http://localhost:9000

logging:
  level:
    org.springframework.security: DEBUG